### ISSUE TITLE
Use shorthand for generating test tuples

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ire#10]
Refactor this method an use for all tests (where applicable): https://github.com/FTSRG/ire/blob/5c574a1894f9e8f95bac4b9ec358a37f3504fb42/src/test/scala/HashAntijoinerTest.scala#L15

**Comment by szarnyasg** [comment]
There are other tests to refactor.

**Comment by wafle** [comment]
What do we gain by refactoring them?

**Comment by szarnyasg** [comment]
1. Readability
2. If we decide to switch from the map-based to representation to a vector-based representation (which should improve performance), we only have to change the `tuple()` method in `TestUtil`: https://github.com/FTSRG/ire/blob/b32ed0551e32728d0703377afc1e5406585abb81/src/test/scala/TestUtil.scala
